/**
 * Created by yeml5 on 2018/4/4.
 */
/*auth*/
export const LOGIN_USER_REQUEST='LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE='LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS';
export const LOGIN_OA_REQUEST='LOGIN_OA_REQUEST';
export const LOGIN_OA_SUCCESS='LOGIN_OA_SUCCESS';
export const LOGIN_OA_FAILURE='LOGIN_OA_FAILURE';
